/api/analytics/prometheus-metrics/virtualservice: 
  entity_name: []
  tenant: ["argocd@np","metrics-monitoring@np"]

/api/analytics/prometheus-metrics/serviceengine:
  entity_name: ['kubenode1--se','kubnode2--se']
  tenant: []
