/api/analytics/prometheus-metrics/virtualservice: 
  entity_name: []
  tenant: ["argocd@dds-np","metrics-monitoring@dds-np"]

/api/analytics/prometheus-metrics/serviceengine:
  entity_name: ['lin2dv2kub3w3--se','lin2dv2kub3w4--se']
  tenant: []
